
class PlasmaCodes:

    CODES = {'G21', 'G91_1', 'G00', 'M05', 'G80', 'G01', 'G04', 'G40', 'M13', 'F', 'G54', 'G49', 'G02', 'M30', 'M03', 'M15', 'G03', 'G90'}
    PREFIX = 'cmd_'
    POSFIX_HELP = '_help'

    def __init__(self, config):
        self.gcode = config.get_printer().lookup_object('gcode')

        for i in self.CODES:
            try:
                self.gcode.register_command(i, getattr(self, self.PREFIX + i), getattr(self, self.PREFIX + i + self.POSFIX_HELP))
            except Exception as e:
                print(str(e))

    def __g_move_cmd(self, gcmd):
        cmd_num = int(gcmd.get('G', None))
        

    cmd_G54_help = "Autogenerated help"
    def cmd_G54(self, gcmd):
        pass

    cmd_G02_help = "Autogenerated help"
    def cmd_G02(self, gcmd):
        pass

    cmd_G03_help = "Autogenerated help"
    def cmd_G03(self, gcmd):
        pass

    cmd_G90_help = "Autogenerated help"
    def cmd_G90(self, gcmd):
        pass

    cmd_G91_1_help = "Autogenerated help"
    def cmd_G91_1(self, gcmd):
        pass

    cmd_G49_help = "Autogenerated help"
    def cmd_G49(self, gcmd):
        pass

    cmd_G21_help = "Autogenerated help"
    def cmd_G21(self, gcmd):
        pass

    cmd_G04_help = "Autogenerated help"
    def cmd_G04(self, gcmd):
        pass

    cmd_F_help = "Autogenerated help"
    def cmd_F(self, gcmd):
        pass

    cmd_G80_help = "Autogenerated help"
    def cmd_G80(self, gcmd):
        pass

    cmd_M15_help = "Autogenerated help"
    def cmd_M15(self, gcmd):
        pass

    cmd_M05_help = "Autogenerated help"
    def cmd_M05(self, gcmd):
        pass

    cmd_G01_help = "Autogenerated help"
    def cmd_G01(self, gcmd):
        params = gcmd.get_command_parameters()
        raw_params = gcmd.get_raw_command_parameters()
        print(dir(gcmd))

    cmd_G40_help = "Autogenerated help"
    def cmd_G40(self, gcmd):
        pass

    cmd_G00_help = "Autogenerated help"
    def cmd_G00(self, gcmd):
        pass

    cmd_M30_help = "Autogenerated help"
    def cmd_M30(self, gcmd):
        pass

    cmd_M13_help = "Autogenerated help"
    def cmd_M13(self, gcmd):
        pass

    cmd_M03_help = "Autogenerated help"
    def cmd_M03(self, gcmd):
        pass


def load_config(config):
    return PlasmaCodes(config)

def load_config_prefix(config):
    return PlasmaCodes(config)

